### ISSUE TITLE
Any chance to just dockerize and publish images with just the api?

### ISSUE THREAD

**Issue by adrianipopescu** [blampe/hearring-aid#22]
Title, basically.

It's easy to find an image for a musicbrainz instance.

**Comment by etfeet** [comment]
Do you mean have in image that doesn't forward to the hosted musicbrains metadata api? and instead allow the nginx proxy forwarding backend be configurable to a self hosted musicbrains mirror?

**Comment by etfeet** [comment]
I can see if we can put together an image for the metadata api proxy. but for now if  you want to host your own musicbrains mirror you can do this:
```
  lidarr:
    image: ghcr.io/linuxserver/lidarr:latest
    depends_on:
     - lidarr-api
    volumes:
      - ./config:/config
      - ./lidarr.pem:/etc/ssl/certs/lidarr.pem:ro
    networks:
      traefik:

  lidarr-api:
    image: nginx:latest
    volumes: 
       - ./lidarr.pem/etc/nginx/ssl/lidarr.pem:ro
       -  ./nginx.conf:/etc/nginx.conf:ro
       - ./lidarr.key:/etc/nginx/ssl/lidarr.key:ro
    networks:
      traefik:
        aliases:
          - api.lidarr.audio
```

alternatively instead of using a network alias for the lidarr api you can port map it then do the following to override what the dns hostname resolves to:

```
    lidarr:
      extra_hosts:
        - api.lidarr.audio:192.168.1.10
```

note that if you don't add the lidarr ssl public cert to the lidarr container `/etc/ssl/certs/` ssl certificate trust store you will need to go to `settings -> geeneral` in liddar and disable certificate verification.

and the nginx proxy config is [here ](https://github.com/blampe/hearring-aid/blob/main/docker/nginx.conf)

and you can generate a self signed for the proxy via:

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout lidarr.key \
      -out lidarr.pem \
      -subj "/CN=api.lidarr.audio"
```
